repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.1
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort

-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.397
    hooks:
    -   id: pyright